// Code generated by go tool dist; DO NOT EDIT.
// This is a bootstrap copy of /Users/zhouxinyu/www/localhost/src/github.com/zxy12/go_duplicate_1_12/src/cmd/compile/main.go

//line /Users/zhouxinyu/www/localhost/src/github.com/zxy12/go_duplicate_1_12/src/cmd/compile/main.go:1
package main

func main() {
	println("main in compile")
}
