// Code generated by go tool dist; DO NOT EDIT.
// This is a bootstrap copy of /Users/zhouxinyu/www/localhost/src/github.com/zxy12/go_duplicate_1_12/src/cmd/cgo/zdefaultcc.go

//line /Users/zhouxinyu/www/localhost/src/github.com/zxy12/go_duplicate_1_12/src/cmd/cgo/zdefaultcc.go:1
// Code generated by go tool dist; DO NOT EDIT.

package main

const defaultPkgConfig = `pkg-config`
func defaultCC(goos, goarch string) string {
	switch goos+`/`+goarch {
	}
	return "clang"
}
func defaultCXX(goos, goarch string) string {
	switch goos+`/`+goarch {
	}
	return "clang++"
}
