// Code generated by go tool dist; DO NOT EDIT.
// This is a bootstrap copy of /Users/zhouxinyu/www/localhost/src/github.com/zxy12/go_duplicate_1_12/src/cmd/internal/objabi/zbootstrap.go

//line /Users/zhouxinyu/www/localhost/src/github.com/zxy12/go_duplicate_1_12/src/cmd/internal/objabi/zbootstrap.go:1
// Code generated by go tool dist; DO NOT EDIT.

package objabi

import "runtime"

const defaultGO386 = `sse2`
const defaultGOARM = `7`
const defaultGOMIPS = `hardfloat`
const defaultGOMIPS64 = `hardfloat`
const defaultGOOS = runtime.GOOS
const defaultGOARCH = runtime.GOARCH
const defaultGO_EXTLINK_ENABLED = ``
const version = `go 1.12 zxy`
const stackGuardMultiplierDefault = 1
const goexperiment = ``
